### PR TITLE
added .editorconfig

### PR DESCRIPTION
**Pull request by ptomulik**
@RealRaven2000 please promise, you'll check [editorconfig plugin](https://github.com/editorconfig/editorconfig-notepad-plus-plus#readme) is installed in your notepad++ :D

### CODE REVIEW

**Comment by RealRaven2000** [comment]
where do I copy this?

**Comment by ptomulik** [comment]
no need to copy I guess, just merge as is, it should work out of box with all editors that support editorconfig.

**Comment by RealRaven2000** [comment]
> no need to copy I guess, just merge as is, it should work out of box with all editors that support editorconfig.

I have added the plugin, now what? I guess I have to edit / copy the file somewhere? I always find it difficult to configure notepad++, it's very convoluted. Sometimes I accidentally creat a new workspace and am left to guess where the old one was stored.

image

**Comment by ptomulik** [comment]
I think, it should load the ``.editorconfig`` automatically. Most editors search upward the directories for the ``.editorconfig`` starting from the directory containing the file being edited. Believe, the "Show EditorConfig settings for this file" should confirm this.

**Comment by ptomulik** [comment]
So, in short, the ``.editorconfig`` in the top-level project's directory shall configure editor while opening any of the project's files.

**Pull request merged**
