### PR TITLE
Remove trailing whitespaces in thunderbird68 branch

### PR DESCRIPTION
**Pull request by ptomulik**
Just a cosmetic change.

### CODE REVIEW

**Comment by RealRaven2000** [comment]
hmm, that's a lot of changes just for addressing white space... on general principle I have nothing against that but it is going to make additional wokr for the reviewers on ATN... I assume you are planning on more substantial patches in the future if you go through that effort? :)

**Comment by ptomulik** [comment]
Sorry,  it's a habit. :)
Yes, I've just started patching filtaQuilla for TB 68.
Another yet "issue" is UNIX/DOS endlines in files (some files have UNIX endings, other DOS CRLF). Quite inconsistent, but I've left them untouched for the moment. :)

**Comment by RealRaven2000** [comment]
> 
> 
> Sorry, it's a habit. :)
> Yes, I've just started patching filtaQuilla for TB 68.
> Another yet "issue" is UNIX/DOS endlines in files (some files have UNIX endings, other DOS CRLF). Quite inconsistent, but I've left them untouched for the moment. :)

Yeah I took over the project from Kent James, and I am using notepad++ under Windows. I also switched from Tab to spaces so you will see some inconcistencies unless you set your tab width to 2 spaces.

**Comment by ptomulik** [comment]
I can fix all of this quite easily.

**Pull request merged**
